# Specify the base Docker image for the pipeline
image: node:latest

# Specify paths to cache between pipeline runs
cache:
  paths:
    - backend/node_modules/ # NPM cache

# Define the different stages of the pipeline
stages:
  - init
  - format
  - build
  - test
  - badge

# Install dependencies in the init stage
install-deps:
  stage: init
  script:
    - cd backend && npm ci # Use `npm ci` instead of `npm i` for faster and more reliable installs
  artifacts:
    paths:
      - backend/node_modules/

# Run prettier and linting in format stage
prettier:
  stage: format
  script:
    - cd backend && npm run prettier > prettier_report.txt || true
  artifacts:
    paths:
      - backend/prettier_report.txt
lint-ts:
  stage: format
  script:
    - cd backend && npm run lint > lint_ts_report.txt || true
  artifacts:
    paths:
      - backend/lint_ts_report.txt

# Build the SCs in the build stage
build:
  stage: build
  script:
    - cd backend && npm run build
  artifacts:
    paths:
      - backend/build

# Run tests in the test stage
test:
  stage: test
  script:
    - cd backend && npm run test > test_report.txt 2>&1 || true
  dependencies:
    - install-deps # Make sure dependencies are installed before running the tests
  artifacts:
    paths:
      - backend/test_report.txt

# Generate badges in the deploy stage
badges:
  stage: badge
  script:
    - cd backend && scripts/gen_badges.sh
  artifacts:
    paths:
      - backend/badge_*.svg
  when: always # Always run the job, even if previous jobs fail
